services:
  backend:
    container_name: bloom-bell-backend
    user: "${UID}:${GID}"
    image: felipessdev/bloom-bell-backend:latest
    volumes:
      - bloom-bell-data:/app/data
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333" # HTTP
      - "3334:3334" # WebSocket
    env_file:
      - .env
    restart: unless-stopped

volumes:
  bloom-bell-data:
